name: CI

on: [workflow_dispatch]

env:
  WEBAPP_PACKAGE_PATH: './published'
  NETCORE_VERSION: '6.0.202'
#   SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

#     - name: Test
#       run: dotnet test --no-restore --verbosity normal

#     - name: Slack Notify CI
#       if: always()
#       uses: adamkdean/simple-slack-notify@master
#       with:
#        channel: '#cicd'
#         status: ${{ job.status }}
#         success_text: 'Build (#${env.GITHUB_RUN_NUMBER}) completed successfully'
#         failure_text: 'Build (#${env.GITHUB_RUN_NUMBER}) failed'
#         cancelled_text: 'Build (#${env.GITHUB_RUN_NUMBER}) was cancelled'
#         fields: |
#           [{ "title": "Action URL", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"}]

    - name: Publish app for deploy
      run: dotnet publish --configuration Release --no-build --output ${{ env.WEBAPP_PACKAGE_PATH }}

    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.WEBAPP_PACKAGE_PATH }}
